# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='pubdate'),
        ),
    ]
